exclude:
  - pygments
  - Makefile
  - Gemfile
  - Gemfile.lock
  - css/use.less
  - css/pygments.less
  - css/pygments.trac.less
  - tinc.yaml
  - README.markdown
highlighter: pygments
markdown: redcarpet
