name:             hspec-discover
version:          2.2.2
license:          MIT
copyright:        (c) 2012-2015 Simon Hengel
author:           Simon Hengel <sol@typeful.net>
maintainer:       Simon Hengel <sol@typeful.net>
category:         Testing
stability:        experimental
homepage:         http://hspec.github.io/
synopsis:         Automatically discover and run Hspec tests
description: |
  Automatically discover and run Hspec tests

  <http://hspec.github.io/hspec-discover.html>

github: hspec/hspec/hspec-discover

extra-source-files:
  - test-data/**/*.hs
  - test-data/**/.placeholder

ghc-options: -Wall

dependencies:
  - base == 4.*
  - filepath
  - directory

library: {}

executables:
  hspec-discover:
    source-dirs:
      - src
      - driver
    main: hspec-discover.hs

tests:
  spec:
    main: Spec.hs
    source-dirs:
      - src
      - test
    dependencies: hspec-meta >= 2.2.0
